name: Build and Push the Docker image to GCP
on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tricustom-demo
      PROJECT_ID: tricustom
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest us-east1-docker.pkg.dev/$PROJECT_ID/tricustom-repository/$IMAGE_NAME:latest
        docker push us-east1-docker.pkg.dev/$PROJECT_ID/tricustom-repository/$IMAGE_NAME:latest
       
